- name: Install Nginx on Ubuntu
  apt:
    name: nginx
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Nginx on CentOS
  yum:
    name: nginx
    state: present
  when: ansible_distribution == "CentOS"

- name: Install Jenkins keyring on Ubuntu
  shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  when: ansible_distribution == "Ubuntu"

- name: Install Jenkins repository on Ubuntu
  shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  when: ansible_distribution == "Ubuntu"

- name: Install openjdk-11-jdk on Ubuntu
  apt:
    name: openjdk-11-jdk
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update package cache on Ubuntu
  apt:
    update_cache: yes

- name: Install Jenkins on Ubuntu
  apt:
    name: jenkins
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Jenkins on CentOS
  yum:
    name: jenkins
    state: present
  when: ansible_distribution == "CentOS"

- name: Create Nginx configuration directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Copy Nginx configuration template
  copy:
    content: |
      server {
        listen {{ nginx_port }};
        server_name {{ jenkins_hostname }};
        location / {
          proxy_pass http://{{ jenkins_ip }}:{{ jenkins_port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    dest: /etc/nginx/conf.d/jenkins.conf
    mode: '0644'
  
- name: Stop Nginx and Jenkins services
  service:
    name: "{{ item }}"
    enabled: true
    state: stopped
  loop:
    - nginx
    - jenkins

- name: Reboot Nginx and Jenkins services
  service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - nginx
    - jenkins  
    
- name: Reboot the system
  reboot:
    name: "{{ item }}"
    enabled: true
    reboot_timeout: 3600
    msg: "Status: Reboot complete for "{{ item }}"
  loop:
    - nginx
    - jenkins    
