- name: Install Nginx on Ubuntu
  become: true
  apt:
    name: nginx
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Nginx on CentOS
  become: true
  yum:
    name: nginx
    state: present
  when: ansible_distribution == "CentOS"

- name: Install Jenkins keyring on Ubuntu
  become: true
  shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  when: ansible_distribution == "Ubuntu"

- name: Install Jenkins repository on Ubuntu
  become: true
  shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  when: ansible_distribution == "Ubuntu"

- name: Install openjdk-11-jdk on Ubuntu
  become: true
  apt:
    name: openjdk-11-jdk
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update package cache on Ubuntu
  become: true
  apt:
    update_cache: yes

- name: Install Jenkins on Ubuntu
  become: true
  apt:
    name: jenkins
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Jenkins on CentOS
  become: true
  yum:
    name: jenkins
    state: present
  when: ansible_distribution == "CentOS"

- name: Configure Jenkins on Ubuntu
  lineinfile:
    path: /etc/default/jenkins
    regexp: 'HTTP_PORT='
    line: 'HTTP_PORT="{{ jenkins_port }}"'
  notify: restart jenkins
  when: ansible_distribution == "Ubuntu"

- name: Configure Nginx on Ubuntu
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/jenkins
  notify: restart nginx
  when: ansible_distribution == "Ubuntu"

- name: Enable Jenkins site in Nginx on Ubuntu
  file:
    src: /etc/nginx/sites-available/jenkins
    dest: /etc/nginx/sites-enabled/jenkins
    state: link
  when: ansible_distribution == "Ubuntu"
